version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: npm test
  randomtest:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/node:8.9
    steps:
     - checkout
     - run: echo "random"
workflows:
 version: 2
  build_test_lint:
    jobs:
     - build
     - randomtest
     - test: #Needs random test to succeed first before it is run.
        requires:
         -randomtest